WITH EmployeeCount AS (
    SELECT d.ID, d.NAME, COUNT(e.ID) AS COUNT_OF_EMPLOYEES_IN_THE_DEPARTMENT
    FROM DEPARTMENT d
    LEFT JOIN EMPLOYEE e ON d.ID = e.DEPT_ID
    GROUP BY d.ID, d.NAME
)
SELECT NAME AS DEPARTMENT_NAME, COUNT_OF_EMPLOYEES_IN_THE_DEPARTMENT
FROM EmployeeCount
ORDER BY COUNT_OF_EMPLOYEES_IN_THE_DEPARTMENT DESC, DEPARTMENT_NAME ASC;
